# Site settings
title: 一直很安静
subtitle: 一转身，一经年，一辈子
keyword: jiaoyilun,焦一伦,上善若水,一直很安静,一转身，一经年，一辈子,魅族,MX4,CM12,CyanogenMod
description: 上善若水的小站
name : 上善若水
email: jiaoyilun@163.com

searchable: true
cloudtag : true

dateStyle: "%F %R"
picServer : 'http://7xol15.com1.z0.glb.clouddn.com/pic-thumbnail'

url: http://jiaoyilun.github.io
github_username:  jiaoyilun
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
highlighter: pygments
# highlighter: rouge
# highlighter: false


JB :
  BASE_PATH : false
  atom_path : /atom.xml

