# Site settings
title: 一直很安静
description: 一转身，一经年，一辈子
email: jiaoyilun@163.com
#dateStyle: "%b %-d, %Y"
dateStyle: "%F %R"
staticServer : http://7xol15.com1.z0.glb.clouddn.com/
staticStyle : "-thumbnail"
picServer : http://7xol15.com1.z0.glb.clouddn.com/pic-thumbnail

# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  jiaoyilun
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
highlighter: pygments
# highlighter: rouge
# highlighter: false
